### ISSUE TITLE
 Convert depth map to point cloud map

### ISSUE THREAD

**Issue by LP940708** [YvanYin/DiverseDepth#13]
Hello author, first of all，thank you for your outstanding work, I used your Git to test on my own data set, the effect is very great; I see that your paper also lists the figures of converting the depth map to point cloud, how did you achieve it, and what software did you use to visualize the point cloud diagram?

**Comment by YvanYin** [comment]
Hi, if you want to reconstruct the point cloud, you should set a virtual focal length and using the following equations to recover x,y.z:
`x = (u-u0)*z /f
y = (v-v0)*z/f
z = depth`
You can save the point cloud in the *.PLY file and visualize it in the meshlab.

**Comment by nithinvenny07** [comment]
may i know how i can get absolute depth from output
Thank You
