### ISSUE TITLE
Couple of questions regarding how to use this

### ISSUE THREAD

**Issue by koenichiwa** [YvanYin/DiverseDepth#15]
Hi Wei Yin,

I'll give a quick paragraph of introduction before I'll pose my questions. I'm a computer science student who's working on a little side project. I made a fairly small script that changes video frames into audio in real time. I'm looking to test it's feasibility for use of object detection through audio. Currently it's working on grayscale images, but I'm trying to change that to depth estimations. That's why I started looking at your code. I'm a bit at a loss how to use it though. I tried looking into your paper, but I can't seem to open it because I'm not allowed on campus due to COVID

Say I have extracted a videoframe in my own python module. How would I convert that image to a depth estimation. Which imports do I need to do and which functions would I need to call?

How would the execution change on a lower resolution. Due to hardware limitations I'm downscaling my frames before rendering my waveforms. Should I run your code over my frames before or after downscaling?

Lastly, if I won't use it for commercial use, am I allowed to use this as part of my program if I want to write a research with it?

Kind regards,
Koen

**Comment by YvanYin** [comment]
Sorry for the late reply.  We have released a quick-start code for the inference.
