### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by andy500** [YvanYin/DiverseDepth#18]
keep getting ModuleNotFoundError: No module named 'Minist_Test when l run python ./Minist_Test/tools/test_depth.py --load_ckpt model.pth why?

**Comment by YvanYin** [comment]
Have you exported the PATHONPATH?

**Comment by andy500** [comment]
yes and still get ModuleNotFoundError: No module named
'lib.multi_depth_model_woauxi'

**Comment by andy500** [comment]
got it to work

**Comment by AJAY31797** [comment]
I am trying to implement the code in window, and I am getting the same error `File "D:\DiversedepthAJ\DiverseDepth\Minist_Test\tools\test_depth.py", line 1, in <module>
    from Minist_Test.lib.diverse_depth_model import RelDepthModel
ModuleNotFoundError: No module named 'Minist_Test'`

I have set the PYTHONPATH to the folder where I have cloned the DiverseDepth, but still getting the error. Any suggestions?

**Comment by AJAY31797** [comment]
@andy500 how did you manage to get it work?
