### ISSUE TITLE
Diverse Data Dataset

### ISSUE THREAD

**Issue by l0stpenguin** [YvanYin/DiverseDepth#2]
Hi,
I cannot find the _diverse data dataset_ you mention in your paper. Can you please share it?

**Comment by YvanYin** [comment]
Hi,
I have not released the dataset. We will release that later. if you need DIML and Taskonomy, I can provide you the links.

**Comment by l0stpenguin** [comment]
I already got the diml dataset from this website:
[https://dimlrgbd.github.io/](https://dimlrgbd.github.io/)
Wanted to have a look at yours. I'll wait until you make it public.

**Comment by YvanYin** [comment]
Hi,
I just directly use the provided depth of DIML.
