### ISSUE TITLE
Part Fore Depth Format

### ISSUE THREAD

**Issue by nmerrill67** [YvanYin/DiverseDepth#20]
Hello, thank you for posting this dataset. I am excited to start working with it, but I have a question about the part fore depth format. Specifically, all of the part fore depth images are 8-bit png files, when depths are typically stored as 16-bit in mm (i.e. multiply by 1e-3 to get to meters). So, I am wondering what the scale is for these 8-bit files? Also, is the scale for part_in and part_out actually 1e-3 like normal? It seems after some inspection that all of the 16-bit depth files in part in and part out have a max value of around 255 like the 8-bit files as well, so it would seem impossible that these depths are in mm. Without an example dataloader here, these things are impossible to determine.

**Comment by YvanYin** [comment]
Hi, thank you for your attention to our work. The depth has been normalized. We used the optical flow to match the uncalibrated stereo images and videos to obtain the inverse depth and then transfer them to depth. Therefore, we cannot get the metric information from such depths.

**Comment by nmerrill67** [comment]
Right, thanks. I guess what I was trying to ask was what scale you were bringing these depthmap files into, but now with the example dataloader available, I can just look at that. Kaizoku ou ni ore wa naru!
