### ISSUE TITLE
virtual camera camera parameters?

### ISSUE THREAD

**Issue by y22ma** [YvanYin/DiverseDepth#21]
In the paper, the author mentioned that the true metric depth is transformed into the perspective of a virtual camera via an affine transformation.

Just wondering what the virtual camera intrinsic parameter is you used for the paper?

**Comment by YvanYin** [comment]
The camera parameters are f=200. The optical center is the image center.

**Comment by dyy0205** [comment]
It's that mean if we don't know a real camera parameter from an image,  then we cannot get translation and scaling from network? By the way,  why *60000？just to generate uint16 png？
