### ISSUE TITLE
Problems of dataset downloading

### ISSUE THREAD

**Issue by tyhuang0428** [YvanYin/DiverseDepth#22]
Your work is excellent, and I appreciate the sharing of your RGB-D dataset. I am wondering if there would be other download links like the google drive link, as the current link seems to be the cloud drive in your school, which is hard to download in Mainland, China.

**Comment by YvanYin** [comment]
I will provide a Baidu link later. Do you have VPN for downloading?

**Comment by tyhuang0428** [comment]
> I will provide a Baidu link later. Do you have VPN for downloading?

Actually I have just found an Austrailan server, the current speed is much faster than before. Anyway, thanks for your help. And I will close the issue.

**Comment by CVRS-CJH** [comment]
> I will provide a Baidu link later. Do you have VPN for downloading?

Hello, could you please provide the link? It is very slow for me to download data. Thanks~

**Comment by YvanYin** [comment]
Hi all,

I have updated the google drive links.

**Comment by puyiwen** [comment]
> Hi all,
> 
> I have updated the google drive links.

google drive opened is None, could you please provide the link again?

**Comment by wangty537** [comment]
excellent work, I want to try some experiments, but the link donot work , can you provide new google drive link , thank you very much
