### ISSUE TITLE
Problem about the depth in sky region.

### ISSUE THREAD

**Issue by CVRS-CJH** [YvanYin/DiverseDepth#23]
https://github.com/YvanYin/DiverseDepth/blob/b88c380ab7c35274e0106a7362604e193d1cd67d/Train/data/diverse_dataset.py#L101
Should the depth of sky Region be set to 10 or 100? Inconsistent code and comments in here.

**Comment by YvanYin** [comment]
We set the depth of sky region to a large value. We have tried both 100 and 10, and they have the similar performance.
