### ISSUE TITLE
Adding more RGB-D data to training

### ISSUE THREAD

**Issue by M1234Thomas** [YvanYin/DiverseDepth#24]
Thanks for your work and publishing your models. I have tested your pre-trained models with some of my images for a different use case. The depth prediction looks promising, but not accurate. I want to train a model by adding some data from my dataset so that it could predict accurate depth. Any suggestions on how to add custom data? Do I need any other files other than the train_annotations.json and valid_annotations.json? 
What is the importance of teacher_curriculum.npy? How do I create this for the custom data?

**Comment by YvanYin** [comment]
Hi,
You can follow the taskonomy/DIML annotations to create paired RGB/Depth annotations. You can customize your dataset part and data augmentation.

**Comment by M1234Thomas** [comment]
Thanks for your response. I have trained a model following the DiverseDepth dataset annotations. The model gives a relative error of around 10%. Do you have any suggestions to improve the accuracy of the model?

**Comment by YvanYin** [comment]
Maybe you can follow our latest work: https://github.com/aim-uofa/AdelaiDepth (LeReS, BoostingDepth)
