### ISSUE TITLE
Any plan to provide the original stereo image pairs of DiverseDepth dataset?

### ISSUE THREAD

**Issue by duxingren14** [YvanYin/DiverseDepth#25]
If the original stereo image pairs are provided, then we can make use of the  recent optical flow models to improve the GT of the depths.

Do you have the plans to release those data?

**Comment by YvanYin** [comment]
Hi Zili, thank your attention to our work. I have lost the original paired stereo data. If you are interested in stereo data, you can get them here: https://www.3dstreaming.org/ and Flickr (https://www.flickr.com/search/?text=Stereoscopic). On Flickr, you have to customize a climbing code.
