### ISSUE TITLE
Using GT surface normals to improve the depth prediction

### ISSUE THREAD

**Issue by M1234Thomas** [YvanYin/DiverseDepth#26]
Thanks for the interesting work. I have found from the paper that the Virtual Normal loss is computed as a difference between the normals of the point clouds generated from the GT depth maps and predicted depth maps. 
I would like to pass the ground truth surface normals instead and compute the loss. Could you give some directions to make these changes?

**Comment by YvanYin** [comment]
If you want to use the surface normal, I suggest aligning the prediction to the ground truth first, and then you can follow my VNL paper to minimize the difference between the predicted surface normal and GT surface normal. You can check the ablation study in VNL paper.
