### ISSUE TITLE
About retraining

### ISSUE THREAD

**Issue by zsy950116** [YvanYin/DiverseDepth#27]
Thanks your amazing work!
I met a problem here. I tried to retrain the network according to the information you provided, but I did not get similar results to the pre-trained model you provided. The results I get are much worse compared to yours. I can't locate where the problem is, can you give me some advice? The results are as follows:
![00001-depth](https://user-images.githubusercontent.com/52944106/187114647-3fe4a385-a6c5-435b-bd90-43275ea6f21c.png)
![00001-depth_oral](https://user-images.githubusercontent.com/52944106/187114652-94cc332d-80bc-4cfe-88b4-7c25968a361f.png)

**Comment by YvanYin** [comment]
It seems your results are very smooth. How do you set your lr and schedule.

**Comment by zsy950116** [comment]
The first result is mine, and the second one is yours. The input rgb image is shown below:
![00001](https://user-images.githubusercontent.com/52944106/187116594-a23c5ef3-95f2-4071-afa1-5d0870fe750d.png)
My prediction results are heavily influenced by the texture information in the image. There are obvious errors in the predicted depth map, such as window frames and other locations where the contrast is obvious. In addition, my predicted results are not as smooth as yours, the results have snow-like noise.
My training strategy is exactly the same as 'train.sh' you provided, so is the training dataset.

**Comment by zsy950116** [comment]
Hello, Do you have some advice for me?

**Comment by YvanYin** [comment]
Hi,
from your results, I believe that your model has not been converged. I recommed you can revise the training schedule. Recently, I found that using AdamW, lr 0.0001, and trained more steps, we can get much better results.

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。
