### ISSUE TITLE
Running Quick Start on Windows

### ISSUE THREAD

**Issue by EODEFX** [YvanYin/DiverseDepth#28]
I'm attempting to run the Quick Start code on windows but keep getting the same error. Since "export" doesn't exist on windows, I tried using "set" instead but that didn't seem to help.

I get this error:
`Traceback (most recent call last):
  File "./Minist_Test/tools/test_depth.py", line 1, in <module>
    from Minist_Test.lib.diverse_depth_model import RelDepthModel
ModuleNotFoundError: No module named 'Minist_Test'`

Am I missing a step in setting up the environment in Conda or is it something else?

**Comment by YvanYin** [comment]
Please set the PYTHONPATH before runing the script.

**Comment by EODEFX** [comment]
I've done that both manually in the system environment variables, and directly in the command line via "setx". Neither way seems to work. Thank you for the reply.

**Comment by EODEFX** [comment]
Finally got it past the first issue of it not recognizing project imports. I think I initially forgot to close and reopen the cmd window after setting the environment variables. Now having an issue with "Torch not compiled with CUDA enabled".

**Comment by EODEFX** [comment]
I also figured out the torch issue, I attempted the specific installation versions you had suggested, but it initially didn't install torchvision because of the deprecated version number. So I just used the pytorch suggested latest version install that you also linked, which let me run the test images just fine. FYI for others:
 `conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
`

**Comment by YvanYin** [comment]
thx for comments.
