### ISSUE TITLE
Scaling and translation factors

### ISSUE THREAD

**Issue by skmhrk1209** [YvanYin/DiverseDepth#5]
Hi, thanks for sharing the code of the paper.
How did you get the scaling and translation factors when evaluating on zero-shot datasets?

**Comment by YvanYin** [comment]
Hi,
We get the scale and shift factor by using a least squares fitting. You can use the numpy function:
np.polyfit(pred_mask, gt_mask, deg=1)

**Comment by skmhrk1209** [comment]
Is it okay to calculate the fitting parameters on zero-shot dataset when zero-shot evaluation?
I'm concerned about it because it is essentially equal to get a prior of zero-shot dataset.
