### ISSUE TITLE
Final result/output

### ISSUE THREAD

**Issue by marcelschilling** [YvanYin/DiverseDepth#6]
In the file `test_any_diversedepth.py`, in a commented line, the output is combined with a tanh-fcn-evaluation.

`pred_depth = torch.nn.functional.tanh(pred_depth) + 1`

Should this be done with every output of the network to get the right disparity scaling?

Thanks in advance.

**Comment by YvanYin** [comment]
Hi, I add this is to make the predicted depth value to be positive. 
You can neglect this.
