### ISSUE TITLE
it seems the test_any_diversedepth doesn't work well

### ISSUE THREAD

**Issue by visonpon** [YvanYin/DiverseDepth#7]
Hi @YvanYin 
Thanks for your excellent work, but when I test your model on my own images,  the results are bad.
Hope you can release the train code~

**Comment by YvanYin** [comment]
You can send me a pic, I can try to test it.

**Comment by visonpon** [comment]
Thanks for your quick response, it's not convenient for me to unload the images, but I can show you the test script that modified based on your's,   Is there anything I ignored? Thanks~
![diversedepth](https://user-images.githubusercontent.com/11517731/83349492-e492b400-a367-11ea-9f36-be45e4a39525.jpg)

**Comment by YvanYin** [comment]
add
rgb = rgb[:, :, ::-1]
after load rgb
