### ISSUE TITLE
Failed to find function: lateral_net.lateral_resnext50_body_32x4d while loading the model

### ISSUE THREAD

**Issue by deepaktammali** [YvanYin/DiverseDepth#8]
ERROR net_tools.py:  32: Failed to f1ind function: lateral_net.lateral_resnext50_body_32x4d
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-34e053950001> in <module>()
----> 1 test_any_diversedepth.RelDepthModel()

2 frames
/content/DiverseDepth/lib/models/diverse_depth_model.py in __init__(self)
     11         super(RelDepthModel, self).__init__()
     12         self.loss_names = ['Virtual_Normal']
---> 13         self.depth_model = DepthModel()
     14 
     15     def forward(self, data):

/content/DiverseDepth/lib/models/diverse_depth_model.py in __init__(self)
    153         #bottom_up_model = 'lateral_net.lateral_' + cfg.MODEL.ENCODER
    154         bottom_up_model = network.__name__.split('.')[-1] + '.lateral_' + cfg.MODEL.ENCODER
--> 155         self.encoder_modules = get_func(bottom_up_model)()
    156         #self.decoder_modules = lateral_net.fcn_topdown(cfg.MODEL.ENCODER)
    157         self.decoder_modules = network.fcn_topdown()

/content/DiverseDepth/lib/utils/net_tools.py in get_func(func_name)
     28         # Otherwise, assume we're referencing a module under modeling
     29         module_name = 'lib.models.' + '.'.join(parts[:-1])
---> 30         module = importlib.import_module(module_name)
     31         return getattr(module, parts[-1])
     32     except Exception:

AttributeError: module 'lib.models.lateral_net' has no attribute 'lateral_resnext50_body_32x4d'

**Comment by YvanYin** [comment]
hi,
It should be lateral_resnext50_32x4d_body_stride16 not the lateral_resnext50_body_32x4d
